# Generated by Django 3.2.9 on 2021-11-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostAPIs', '0002_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='long',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='town',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='zip_code',
        ),
    ]
