# Generated by Django 3.2.9 on 2021-11-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostAPIs', '0003_auto_20211113_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='compound',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='neg',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='neu',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='pos',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
